[MeterV3H2]
ToolTipType=1
ToolTipText="Click here to edit your wallet address#CRLF#then paste your address#CRLF#then press Enter#CRLF#P.S. address reset after reopen\update skin#CRLF#(need Save)"

[MeterV3H3]
ToolTipType=1
ToolTipText="After you click here#CRLF#your address will save to skin .ini file#CRLF#and NOT reset after you reopen rainmeter"

[MeterV3H4]
ToolTipType=1
ToolTipText="If you want for some reason to#CRLF#delete address from .ini file#CRLF#JUST DO IT (click)"