[MeterV2H3_1_Diff]
ToolTipType=1
ToolTipText="Left click to change between#CRLF#Current network Difficulty#CRLF#and Last Block time pool find ago"

[MeterV2H3_2_Diff]
ToolTipType=1
ToolTipText="Left click to change between#CRLF#Current network Difficulty#CRLF#and Last Block time pool find ago"

[MeterV2H3_1_LastBlockTime]
ToolTipType=1
ToolTipText="Left click to change between#CRLF#Current network Difficulty#CRLF#and Last Block time pool find ago"

[MeterV2H3_2_LastBlockTime]
ToolTipType=1
ToolTipText="Left click to change between#CRLF#Current network Difficulty#CRLF#and Last Block time pool find ago"
