[MeterV2H4_1_DUE]
ToolTipType=1
ToolTipText="Left click to change between#CRLF#Your total Paid#CRLF#and Your total Due"

[MeterV2H4_2_DUE]
ToolTipType=1
ToolTipText="Left click to change between#CRLF#Your total Paid#CRLF#and Your total Due"

[MeterV2H4_1_PAID]
ToolTipType=1
ToolTipText="Left click to change between#CRLF#Your total Paid#CRLF#and Your total Due"

[MeterV2H4_2_PAID]
ToolTipType=1
ToolTipText="Left click to change between#CRLF#Your total Paid#CRLF#and Your total Due"

