[MeterV1H2]
ToolTipType=1
ToolTipText="Left click to change between Price#CRLF#Profit per Day#CRLF#Profit per Month"

[MeterV1H3]
ToolTipType=1
ToolTipText="Left click to change between Price#CRLF#Profit per Day#CRLF#Profit per Month"

[MeterV1H4]
ToolTipType=1
ToolTipText="Left click to change between Price#CRLF#Profit per Day#CRLF#Profit per Month"

[MeterV1H5]
ToolTipType=1
ToolTipText="Left click to change between Price#CRLF#Profit per Day#CRLF#Profit per Month"

[MeterV1H2_DayReward]
ToolTipType=1
ToolTipText="Left click to change between Price#CRLF#Profit per Day#CRLF#Profit per Month"

[MeterV1H3_DayReward]
ToolTipType=1
ToolTipText="Left click to change between Price#CRLF#Profit per Day#CRLF#Profit per Month"

[MeterV1H2_DayProfit]
ToolTipType=1
ToolTipText="Left click to change between Price#CRLF#Profit per Day#CRLF#Profit per Month"

[MeterV1H3_DayProfit]
ToolTipType=1
ToolTipText="Left click to change between Price#CRLF#Profit per Day#CRLF#Profit per Month"

[MeterV1H2_MonthReward]
ToolTipType=1
ToolTipText="Left click to change between Price#CRLF#Profit per Day#CRLF#Profit per Month"

[MeterV1H3_MonthReward]
ToolTipType=1
ToolTipText="Left click to change between Price#CRLF#Profit per Day#CRLF#Profit per Month"

[MeterV1H2_MonthProfit]
ToolTipType=1
ToolTipText="Left click to change between Price#CRLF#Profit per Day#CRLF#Profit per Month"

[MeterV1H3_MonthProfit]
ToolTipType=1
ToolTipText="Left click to change between Price#CRLF#Profit per Day#CRLF#Profit per Month"































